name: Build Wheels

on:
  push:
    branches:
      - main
      - master
      - serialization

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    if: github.repository_owner == 'rleap-project'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies and requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install setuptools wheel twine cibuildwheel


    - name: Build wheels
      run: cibuildwheel --platform linux --output-dir wheelhouse
      env:
        CIBW_BUILD_VERBOSITY: "1"
        CIBW_BEFORE_BUILD: |
          yum install -y wget
          bash .github/workflows/scripts/install_boost.sh
        CIBW_ENVIRONMENT: BOOST_ROOT="/project/boost_1_82_0"

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ wheelhouse/*
